dist: bionic # https://docs.travis-ci.com/user/reference/bionic/
language: java
jdk: openjdk10 # https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
sudo: false
script:
  - mvn -version
  - mvn -f pom_travis.xml clean package # https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
